---

- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Create Dir to Downlaod Tomcat.
    file: path=/opt/SP/apps/tomcat state=directory

  - name: Install Java 1.8
    apt: name=default-jdk state=present

    
  - name: Remove ROOT folder initially
    command: rm -rf /opt/SP/apps/tomcat/webapps/ROOT
  
  - name: Copy Project War Files
    copy: src=/var/lib/jenkins/workspace/war-storage-uat/{{ QABuild }}/debitcardcustomer-0.0.1-SNAPSHOT.war dest=/opt/SP/apps/tomcat/webapps/ROOT.war mode=0644
    notify:
    - Restart Tomcat

  handlers:
  - name: Restart Tomcat
    shell: "nohup sh /opt/SP/apps/tomcat/bin/catalina.sh start"
